# Configuration for team challenges
teams:
  - TeamAlpha:email1@gmail.com,email2@gmail.com
  - TeamBeta:email1@gmail.com,email2@gmail.com
  - TeamGamma:email1@gmail.com,email2@gmail.com
  - TeamDelta:email1@gmail.com,email2@gmail.com
  - TeamEpsilon:email1@gmail.com,email2@gmail.com

phases:
  phase1:
    - web-exploitation
    - cryptography
    - forensics
    - binary-analysis
  
  phase2:
    - advanced-web
    - reverse-engineering
    - network-security
    - steganography
    - privilege-escalation
  
  phase3:
    - final-challenge-1
    - final-challenge-2
    - capstone-project
