#!/bin/bash

origin="$(pwd)"
path="$1"
if [ "$1" = "" ]; then
    path="."
fi

cd $path
path=$(pwd)

if [ ! -d "$path/private" ]; then
    git clone https://github.com/CTFd/CTFd.git "$path/private"
    cat "$origin/docker-compose.yml" | \
        sed "s|{{secretKey}}|$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 64; echo)|g" | \
        sed 's|{{number}}|0|g' > "$origin/docker-compose-pri.yml"
fi

if [ ! -d "$path/public" ]; then
    cp -r "$path/private" "$path/public"
    cat "$origin/docker-compose.yml" | \
        sed "s|{{secretKey}}|$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 64; echo)|g" | \
        sed 's|{{number}}|1|g' > "$origin/docker-compose-pub.yml"
fi


echo "Change database secrets"
read -p "Continue?: "

echo "Loading private docker compose configuration..."
cd $path/private
rm docker-compose.yml
cp $origin/compose/docker-compose-pri.yml ./docker-compose.yml

echo "Loading public docker compose configuration..."
cd $path/public
rm docker-compose.yml
cp $origin/compose/docker-compose-pub.yml ./docker-compose.yml

echo "Starting platforms..."
docker compose up --build -d
cd $path/private
docker compose up --build -d

echo "Have you set the teams.json and users.json files?"
read -p "Continue?: "

echo "Creating private platform configuration..."
cd $origin/config/
zip -qr setup-new.zip db uploads
cd ..
echo "Setup is in: $(pwd)/config/setup-new.zip"

