#!/bin/bash

origin="$(pwd)"
piston_dir="$(pwd)/piston/"
if [ -d $piston_dir ]; then
    read -p "Piston already exists on path, Delete [y/n]: " answer
    if [ "$answer" = "y" ]; then
        sudo rm -rf $piston_dir
        echo "Cloning piston repo..."
        git clone https://github.com/engineer-man/piston $piston_dir
    fi
else
    echo "Cloning piston repo..."
    git clone https://github.com/engineer-man/piston $piston_dir
fi
cd $piston_dir
docker compose up -d api
cd cli
npm i
cd -
echo "Started python installation..."
cli/index.js ppman install python &
echo "Started go installation..."
cli/index.js ppman install go &
echo "Started gcc installation..."
cli/index.js ppman install gcc &
echo "Started node installation..."
cli/index.js ppman install node &
wait
echo "Packages installed successfully you can run compose..."
docker compose down
docker container rm -f piston_api
cd $origin
echo "Generating compose file..."
cat ./compose.yaml.tmpl | sed "s|{{PACKAGES_DIR}}|$piston_dir/data/piston/packages" > compose.yaml
