author: youness
category: devops
connection_info: docker pull ymerzouka/fidelius-charm:latest
description: "Neville Longbottom attempted to secure a vital flag with a Digital Fidelius\
  \ in the Main service,\nbut something isn't quite right \u2013 the necessary resources\
  \ from the Caller service aren't making it through.\nCan you provide the Main service\
  \ with the necessary resources and retrieve the hidden flag?\n"
files:
- /home/merzouka/code/inge/neer/setup/challenges/../../challenges/devops/the-fidelius-charm/files/inspect.json
flags:
- 1ng3neer2k25{w311_it_w0rk5_0n_my_m4ch1n3}
hints:
- even containers have a history
name: The Fidelius Charm
state: hidden
tags:
- medium
- youness
- devops
topics:
- devops
- docker
- compose
type: standard
value: 200
version: '0.1'
