#!/bin/bash

CTFCLI_CONFIG="$(pwd)/configs"

if [ "$1" = "" ]; then
    echo "Please specify visibility: private/public..."
    exit 1
fi

if [ "$1" = "private" ]; then
    if [ -d .ctf ]; then
        rm -r ./.ctf/
    fi
    cp -r $CTFCLI_CONFIG/.private ./.ctf
    echo "Changed to private configuration"
else
    if [ -d .ctf ]; then
        rm -r ./.ctf/
    fi
    cp -r $CTFCLI_CONFIG/.public ./.ctf
    echo "Changed to public configuration"
fi
