#!/bin/bash

CTFCLI_CONFIG="$(pwd)/configs"

if [ "$1" = "" ]; then
    echo "Please specify visibility: private/public..."
    exit 1
fi

if [ "$1" = "private" ]; then
    mv $CTFCLI_CONFIG/.private ./.ctf
    echo "Changed to private configuration"
else
    mv $CTFCLI_CONFIG/.public ./.ctf
    echo "Changed to public configuration"
fi
