#!/bin/bash

CTFCLI_CONFIG="$(pwd)/configs"

if [ -f "./.env" ]; then
    source ./api
fi

if [ "$1" = "" ]; then
    echo "Please specify visibility: private/public..."
    exit 1
fi

if [ "$1" = "private" ]; then
    if [ -d .ctf ]; then
        rm -r ./.ctf/
    fi
    cp -r $CTFCLI_CONFIG/.private ./.ctf
    printf "CTFD_URL=http://127.0.0.1:8000\nAUTH_TOKEN=$PRIVATE_AUTH_TOKEN\nENVIRONMENT=$ENVIRONMENET" > ./.env
    echo "Changed to private configuration"
else
    if [ -d .ctf ]; then
        rm -r ./.ctf/
    fi
    cp -r $CTFCLI_CONFIG/.public ./.ctf
    printf "CTFD_URL=http://127.0.0.1:8001\nAUTH_TOKEN=$PUBLIC_AUTH_TOKEN\nENVIRONMENT=$ENVIRONMENET" > ./.env
    echo "Changed to public configuration"
fi
